# Generated by Django 4.0.5 on 2022-06-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
