name: mangaonline

services:

  mysql:
    image: mysql
    container_name: mydb
    ports: 
      - "3306:3306/tcp"
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql

  django: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: myweb
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
      MYSQL_HOST: ${HOST_IP}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data: