# Generated by Django 4.0.5 on 2022-06-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userbase',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='userbase',
            name='cap_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
