# Generated by Django 4.0.5 on 2022-06-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userbase_managers_alter_userbase_cap_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
