# Generated by Django 4.0.5 on 2022-06-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userbase_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
