# Generated by Django 4.1 on 2022-08-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userbase_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='about',
        ),
    ]
