# Generated by Django 4.1 on 2022-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userbase_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
